### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by artvolk** [littleK0i/jqGridPHP#1]
Hello!

jqGridPHP is wonderful! Really!

I've found some minor documentation errors in wiki (http://jqgrid-php.net/)
1. Here:
   http://jqgrid-php.net/doku.php?id=wiki:pagination

``` PHP
protected function buildOrderBy($sidx, $sord)
{
    if(in_array($sidx, array('user_id', 'post_id')))
    {
        return "category ASC, $sidx $sord, id DESC";
    }
    else
    {
        return parent::buildOrderBy($sidx, $sord);
    }
}
```

One should return  `return "ORDER BY category ASC, $sidx $sord, id DESC";`
1. Here: http://jqgrid-php.net/doku.php?id=wiki:col-manual

Signature of should be the following:

`protected function parseRow(array $r)` (PHP Type Hinting missed in example, but exists in base class.

**Comment by littleK0i** [comment]
Thanks for your feedback. :)
1. Fixed.
2. Fixed.

Actually, **parseRow** is not meant to be called in child classes directly. Not much use in type hinting here. I usually skip it in my examples to make the code shorter.

**Comment by artvolk** [comment]
Thank you for the quick response!

Is there any better way then overriding `parseRow` in child classes?

P.S. И чего это мы на английском, ну да ладно :)

**Comment by littleK0i** [comment]
Вопрос в том, что `parseRow` в норме не должно напрямую вызываться разработчиком.
Единственное место, где происходит её вызов: `addRow`.

Если не менять механизм добавления рядов (не переписывать `addRow`), то в `parseRow` всегда будет приходить массив. Можно смело на это рассчитывать. Поэтому type hinting ничего особо не дает. Но и хуже от него не будет :)

Вообще, единственное назначение `parseRow` - сократить вот такой код из каждого второго грида:

``` PHP
protected function addRow($r)
{
    $r['foo'] = 'bar';
    return parent::addRow($r);
}
```

чтобы не надо было постоянно помнить о необходимости вызвать parent::addRow.

**Comment by artvolk** [comment]
> Поэтому type hinting ничего особо не дает. Но и хуже от него не будет :)

Проблема была в том, что на PHP 5.3 с сообщениями об ошибках по максимуму (E_STRICT и всё остальное),  ругается, что сигнатуры в базовом классе и моём наследники отличаются, поэтому и заметил :)

> Вопрос в том, что parseRow в норме не должно напрямую вызываться разработчиком.
> Единственное место, где происходит её вызов: addRow.

Мне этот метод понадобился, чтобы добавить в ячейку custom HTML, который собирается частично из данных невидимых колонок (форматтеры, определённые на JS не совсем подходят, выделение цветом, которое есть как плагин в клиентской части jqGridPHP тоже). Или есть какой-то более правильный способ это сделать?

**Comment by littleK0i** [comment]
> Или есть какой-то более правильный способ это сделать?

Все правильно. `parseRow` для этого и нужен.
Сейчас уберу type hinting из базового класса.

**Comment by artvolk** [comment]
Спасибо большое за ответы!

**Comment by artvolk** [comment]
Да, забыл закрыть :)
